# Generated by Django 5.1 on 2026-02-20 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaltiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(max_length=255, unique=True)),
                ('purchase_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('fee', models.PositiveIntegerField(default=0)),
                ('refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khalti_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_kh_status_851048_idx'), models.Index(fields=['created_at'], name='payments_kh_created_6c3123_idx'), models.Index(fields=['transaction_id'], name='payments_kh_transac_9f6457_idx')],
            },
        ),
    ]
