# Generated by Django 6.0.1 on 2026-02-11 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_intent_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
