# Generated by Django 6.0.1 on 2026-02-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_add_created_at_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatsession',
            name='last_interaction',
        ),
    ]
