# Generated by Django 6.0.1 on 2026-01-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodanalysis',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
